name: Node CI
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: echo ${{ secrets.NPM_TOKEN }}
      - run: npm install
      - run: npm run build
