name: OpenSSF Scorecard

on:
  branch_protection_rule:
  push:
    branches: [main]
  schedule:
    - cron: "24 3 * * 1"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scorecard:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
      security-events: write
    steps:
      - name: Checkout
        # actions/checkout@v4
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Run OpenSSF Scorecard
        # ossf/scorecard-action@v2.4.3
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload SARIF results
        # github/codeql-action/upload-sarif@v3
        uses: github/codeql-action/upload-sarif@03e4368ac7daa2bd82b3e85262f3bf87ee112f57
        with:
          sarif_file: results.sarif
